# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Matthew Ruffell
tagline:          'Security Researcher'
description:      'Sustaining Engineer @ <a href="https://canonical.com">Canonical</a>.<br>Kernel Developer. Reverse Engineer.<br>Founder of <a href="https://dapperlinux.com">Dapper Linux</a>.'
url:              https://ruffell.nz
#baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Matthew Ruffell'
  url:            https://ruffell.nz

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
                    
remote_theme: fongandrew/hydeout

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                                
excerpt_separator: <!--more-->
